# 科学計算

In [1]:
a = Vector(1:3)

3-element Vector{Int64}:
 1
 2
 3

In [2]:
b = Vector(4:6)

3-element Vector{Int64}:
 4
 5
 6

In [3]:
[a b]

3×2 Matrix{Int64}:
 1  4
 2  5
 3  6

In [4]:
A = [1 2 3;
4 5 6;
7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [5]:
A[1]

1

In [6]:
A[1, 1]

1

In [7]:
A = Vector(1:9)

9-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [8]:
A[begin]

1

In [9]:
A[end]

9

In [10]:
A[begin:end]

9-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [11]:
a = Vector(1:9)

9-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [12]:
a[2] = 0

0

In [13]:
a

9-element Vector{Int64}:
 1
 0
 3
 4
 5
 6
 7
 8
 9

In [14]:
a .+ 1

9-element Vector{Int64}:
  2
  1
  4
  5
  6
  7
  8
  9
 10

In [15]:
a[a .> 4] .= 0

5-element view(::Vector{Int64}, [5, 6, 7, 8, 9]) with eltype Int64:
 0
 0
 0
 0
 0

In [16]:
a

9-element Vector{Int64}:
 1
 0
 3
 4
 0
 0
 0
 0
 0

In [17]:
A = reshape(1:9, 3, 3)

3×3 reshape(::UnitRange{Int64}, 3, 3) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

In [18]:
collect(A)

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [19]:
A = rand(3, 3)

3×3 Matrix{Float64}:
 0.214816   0.537274  0.455798
 0.703125   0.645713  0.283877
 0.0670951  0.181663  0.908729

In [21]:
view(A, :, 1)

3-element view(::Matrix{Float64}, :, 1) with eltype Float64:
 0.21481613309920977
 0.7031247847609119
 0.06709508493743455

In [22]:
A = collect(reshape(1:9, 3, 3))

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [23]:
view(A, :, 1)

3-element view(::Matrix{Int64}, :, 1) with eltype Int64:
 1
 2
 3

In [24]:
A

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9