In [1]:
[1]

1-element Vector{Int64}:
 1

In [2]:
[1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [3]:
Float64[4, 5, 6]

3-element Vector{Float64}:
 4.0
 5.0
 6.0

In [4]:
[1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [5]:
[1 2
3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [6]:
A = [1 2 3
4 5 6
7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [7]:
A[1, 1]

1

In [8]:
A[2, 1]

4

# 初期化

In [9]:
Array{Float32}(undef, 3, 4)

3×4 Matrix{Float32}:
 4.04781f-19  1.0f-45     2.47004f-17  1.0f-45
 1.0f-45      6.02316f27  1.0f-45      0.0
 4.9466f-25   1.0f-45     2.47005f-17  0.0

In [10]:
zeros(Float32, 2, 3)

2×3 Matrix{Float32}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [11]:
ones(Float32, 2, 3)

2×3 Matrix{Float32}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [12]:
randn(Float32, 3, 3)

3×3 Matrix{Float32}:
  0.0664235  -2.02526   -1.36911
  1.01714    -0.345146   1.48595
 -1.30706     1.22949   -2.03104

In [13]:
fill(100, 3, 3)

3×3 Matrix{Int64}:
 100  100  100
 100  100  100
 100  100  100

In [14]:
A = [1 2 3 4;
5 6 7 8;
9 10 11 12]

3×4 Matrix{Int64}:
 1   2   3   4
 5   6   7   8
 9  10  11  12

In [15]:
reshape(A, 4, 3)

4×3 Matrix{Int64}:
 1   6  11
 5  10   4
 9   3   8
 2   7  12

# コピー

In [16]:
A = randn(3, 3)

3×3 Matrix{Float64}:
  0.968746   0.356863  -1.53534
 -1.60384   -0.59292    0.289343
  1.39143    1.48968    1.65369

In [17]:
B = A

3×3 Matrix{Float64}:
  0.968746   0.356863  -1.53534
 -1.60384   -0.59292    0.289343
  1.39143    1.48968    1.65369

In [18]:
B[1, 1] = 1

1

In [19]:
B

3×3 Matrix{Float64}:
  1.0       0.356863  -1.53534
 -1.60384  -0.59292    0.289343
  1.39143   1.48968    1.65369

In [20]:
A

3×3 Matrix{Float64}:
  1.0       0.356863  -1.53534
 -1.60384  -0.59292    0.289343
  1.39143   1.48968    1.65369

In [21]:
A = randn(3, 3)
B = copy(A)

3×3 Matrix{Float64}:
 -1.54569   -0.111853   1.95183
  0.382264  -1.21959   -1.20173
  1.06326   -0.139672   1.02184

In [22]:
B[1, 1] = 1

1

In [23]:
B

3×3 Matrix{Float64}:
 1.0       -0.111853   1.95183
 0.382264  -1.21959   -1.20173
 1.06326   -0.139672   1.02184

In [24]:
A

3×3 Matrix{Float64}:
 -1.54569   -0.111853   1.95183
  0.382264  -1.21959   -1.20173
  1.06326   -0.139672   1.02184

In [25]:
A = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [26]:
hoge = [1]

1-element Vector{Int64}:
 1

In [27]:
A = [hoge, hoge, hoge]

3-element Vector{Vector{Int64}}:
 [1]
 [1]
 [1]

In [28]:
B = copy(A)

3-element Vector{Vector{Int64}}:
 [1]
 [1]
 [1]

In [29]:
B

3-element Vector{Vector{Int64}}:
 [1]
 [1]
 [1]

In [30]:
B[1][1]

1

In [31]:
B[1][1] = 2

2

In [32]:
B

3-element Vector{Vector{Int64}}:
 [2]
 [2]
 [2]

In [33]:
A

3-element Vector{Vector{Int64}}:
 [2]
 [2]
 [2]

In [34]:
hoge = [3]

1-element Vector{Int64}:
 3

In [35]:
A = [hoge, hoge, hoge]

3-element Vector{Vector{Int64}}:
 [3]
 [3]
 [3]

In [36]:
B = deepcopy(A)

3-element Vector{Vector{Int64}}:
 [3]
 [3]
 [3]

In [37]:
B

3-element Vector{Vector{Int64}}:
 [3]
 [3]
 [3]

In [38]:
B[1][1] = 0

0

In [39]:
B

3-element Vector{Vector{Int64}}:
 [0]
 [0]
 [0]

In [40]:
A

3-element Vector{Vector{Int64}}:
 [3]
 [3]
 [3]

# 配列演算

In [41]:
A = ones(Float32, 3, 3)

3×3 Matrix{Float32}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [42]:
B = fill(2.0, 3, 3)

3×3 Matrix{Float64}:
 2.0  2.0  2.0
 2.0  2.0  2.0
 2.0  2.0  2.0

In [43]:
A + B

3×3 Matrix{Float64}:
 3.0  3.0  3.0
 3.0  3.0  3.0
 3.0  3.0  3.0

In [44]:
A - B

3×3 Matrix{Float64}:
 -1.0  -1.0  -1.0
 -1.0  -1.0  -1.0
 -1.0  -1.0  -1.0

In [45]:
A * B

3×3 Matrix{Float64}:
 6.0  6.0  6.0
 6.0  6.0  6.0
 6.0  6.0  6.0

In [46]:
C = 10

10

In [47]:
C * A

3×3 Matrix{Float32}:
 10.0  10.0  10.0
 10.0  10.0  10.0
 10.0  10.0  10.0

In [48]:
A = ones(Float32, 3, 3)

3×3 Matrix{Float32}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [49]:
B = fill(2, 3)

3-element Vector{Int64}:
 2
 2
 2

In [50]:
A + B

LoadError: DimensionMismatch("dimensions must match: a has dims (Base.OneTo(3), Base.OneTo(3)), must have singleton at dim 2")

In [51]:
A.+ B

3×3 Matrix{Float32}:
 3.0  3.0  3.0
 3.0  3.0  3.0
 3.0  3.0  3.0

In [52]:
A .- B

3×3 Matrix{Float32}:
 -1.0  -1.0  -1.0
 -1.0  -1.0  -1.0
 -1.0  -1.0  -1.0

In [53]:
A * B

3-element Vector{Float32}:
 6.0
 6.0
 6.0

In [54]:
C = 10

10

In [55]:
A + C

LoadError: MethodError: no method matching +(::Matrix{Float32}, ::Int64)
For element-wise addition, use broadcasting with dot syntax: array .+ scalar
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:560
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:87
  +(::T, ::Integer) where T<:AbstractChar at char.jl:223
  ...

In [56]:
A .+ C

3×3 Matrix{Float32}:
 11.0  11.0  11.0
 11.0  11.0  11.0
 11.0  11.0  11.0

In [57]:
A ./ C

3×3 Matrix{Float32}:
 0.1  0.1  0.1
 0.1  0.1  0.1
 0.1  0.1  0.1

# 配列に関する関数

In [58]:
A = rand(3, 3)

3×3 Matrix{Float64}:
 0.960053   0.732636  0.729041
 0.0707417  0.474344  0.626627
 0.897371   0.789954  0.75873

In [59]:
map(x -> x * 10, A)

3×3 Matrix{Float64}:
 9.60053   7.32636  7.29041
 0.707417  4.74344  6.26627
 8.97371   7.89954  7.5873

In [60]:
A = Vector(1:5)

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [61]:
push!(A, 0)

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 0

In [62]:
pop!(A)

0

In [63]:
A

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [64]:
reduce(*, A)

120

In [65]:
reduce(+, A)

15

In [66]:
A = Vector(1:10)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [67]:
filter(isodd, A)

5-element Vector{Int64}:
 1
 3
 5
 7
 9

In [68]:
filter(iseven, A)

5-element Vector{Int64}:
  2
  4
  6
  8
 10

In [69]:
size(A)

(10,)

In [70]:
length(A)

10

In [71]:
A = Vector(5:-1:1)

5-element Vector{Int64}:
 5
 4
 3
 2
 1

In [72]:
sort(A)

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [73]:
sort(A, rev=true)

5-element Vector{Int64}:
 5
 4
 3
 2
 1